{
 "title": "Windows Bench Metrics",
 "description": "This dashboard is to display the metrics from windows bench",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP, instance)"
    }
   },
   { "name": "gpu", "query": { "query": "label_values(gpu)" } },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   },
   {
    "name": "server",
    "label": "server",
    "query": {
     "query": "label_values(windows_system_system_up_time,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Docker metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "expr": "container_state_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Not running",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "expr": "container_state_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "load 1m" }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Prometheus Exporter Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 20, "y": 1 },
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "container_state_status{name=~\".+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image!=\"\",container_label_org_label_schema_group=\"\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "table",
   "gridPos": { "h": 11, "w": 13, "x": 10, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[1m])) by (name) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_usage_bytes{name=~\".+\"}) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=~\".+\"}[1m])) by (name)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=~\".+\"}[1m])) by (name)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[1m])) by (name)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[1m])) by (name)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[15m])) by (name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Hardware metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(windows_cpu_time_total{instance=\"$server\", mode!=\"idle\"}[30s])) / on(instance) group_left sum by (instance)((irate(windows_cpu_time_total{instance=\"$server\"}[30s])))) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((windows_os_physical_memory_free_bytes{instance=\"$server\"} * 100) / windows_cs_physical_memory_bytes{instance=\"$server\"})"
    }
   ]
  },
  {
   "title": "GPU Usage Panel",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL) by (gpu)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VRAM utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_MEM_COPY_UTIL) by (gpu)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 3, "x": 20, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "legendFormat": "Busy System" },
    {
     "expr": "sum by(instance) (irate(windows_cpu_time_total{instance=\"$server\", mode=\"user\"}[30s])) / on(instance) group_left sum by (instance)((irate(windows_cpu_time_total{instance=\"$server\"}[30s])))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by(instance) (irate(windows_cpu_time_total{instance=\"$server\", mode=\"iowait\"}[30s])) / on(instance) group_left sum by (instance)((irate(windows_cpu_time_total{instance=\"$server\"}[30s])))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by(instance) (irate(windows_cpu_time_total{instance=\"$server\", mode=~\".*irq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(windows_cpu_time_total{instance=\"$server\"}[$__rate_interval])))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by(instance) (irate(windows_cpu_time_total{instance=\"$server\", mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[30s])) / on(instance) group_left sum by (instance)((irate(windows_cpu_time_total{instance=\"$server\"}[30s])))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by(instance) (irate(windows_cpu_time_total{instance=\"$server\", mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(windows_cpu_time_total{instance=\"$server\"}[30s])))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{instance=\"$server\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "windows_cs_physical_memory_bytes{instance=\"$server\"} - windows_os_physical_memory_free_bytes{instance=\"$server\"}\r\n",
     "legendFormat": "RAM Used"
    },
    { "legendFormat": "RAM Cache + Buffer" },
    {
     "expr": "windows_os_physical_memory_free_bytes{instance=\"$server\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(windows_os_virtual_memory_bytes{instance=\"$server\"} - windows_os_virtual_memory_bytes{instance=\"$server\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MEMORY_TEMP{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory Bandwidth Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MEM_COPY_UTIL{instance=~\"${instance}\", gpu=~\"${gpu}\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  }
 ]
}